[WIP] initial dockerfile
Elchin/permamodel_docker pull request #1
Opened 2017-08-02 22:29 UTC by dayne

Getting basic dockerfile.

Need somebody else to test and verify before we merge.

2017-08-02 22:31 UTC, dayne commented
@sc0tts can you review

2017-08-03 00:46 UTC, sc0tts requested changes
I recommend the following changes:

1) Separate the RUN commands so they succeed/fail independently

2) Change the 'apt' commands back to 'apt-get'

3) Change option "-q" to "-qy" on the apt(-get) update RUN command

Other than that...looks great -- and runs successfully for me!

2017-08-03 01:49 UTC, sc0tts approved these changes

2017-08-03 01:50 UTC, sc0tts commented
Looks good:  :shipit:

2017-08-03 12:42 UTC, merged